### ISSUE TITLE
Error when getting price Dreams & Nightmares Case

### ISSUE THREAD

**Issue by spabaex** [tncykrkyl/csgo-advanced-drop#1]
Error when getting price "Dreams & Nightmares " Case
All other prices parsing fine, but price "Dreams & Nightmares Case" return **-**.

**Comment by oppars01** [comment]
It was an error and could not draw the price, as it was the first time "&" was in the cash register names. But 1 month ago, I added a section there for a small update. Have you tried using the latest update?

**Comment by spabaex** [comment]
> It was an error and could not draw the price, as it was the first time "&" was in the cash register names. But 1 month ago, I added a section there for a small update. Have you tried using the latest update?

Yep, your last february update, I compiled it yesterday.
In addition, I noticed that getting price for CS:GO Weapon Case, CS:GO Weapon Case 2, CS:GO Weapon Case 3 also does not work. =`(

**Comment by crashzk** [comment]
I also tested this change that quoted **@tncykrkyl** and it didn't work.

And as **@spabaex** mentioned, there are other items that don't show price too.

![image](https://user-images.githubusercontent.com/32937653/169845551-c1bd9c29-66e7-418f-aaf4-a528882f3573.png)

![image](https://user-images.githubusercontent.com/32937653/169846163-5d50aac8-5cdb-407d-87a5-089e33479db6.png)

![image](https://user-images.githubusercontent.com/32937653/169846251-28e991ac-22cf-447a-b120-23c55d19495c.png)

![image](https://user-images.githubusercontent.com/32937653/169846349-a03c757b-4875-40fb-9d94-94d332090d14.png)

**Comment by oppars01** [comment]
Let me check if the names of the wrong safes are available.

**Comment by crashzk** [comment]
> Let me check if the names of the wrong safes are available.

I'll be waiting, thank you.

**Comment by oppars01** [comment]
![image](https://user-images.githubusercontent.com/89659705/170355026-25915117-8bd9-4e54-86f7-7c6503104be2.png)
There was a problem in the URL encode function because the input and output were the same. When I change it and try it with fake drop, it seems like it can shoot without any problems. You can test it too.

**Comment by crashzk** [comment]
Thanks.  I'll be testing it and get back to you with feedback as soon as possible.

**Comment by crashzk** [comment]
**@tncykrkyl** all right now, thanks.

I also saw that added support for NomPrime players not to receive drop notices, since they don't receive CSGO drops, perfect too.

**Comment by crashzk** [comment]
Fix, this issues can be closed now.
