### ISSUE TITLE
HTTP ERROR 500 

### ISSUE THREAD

**Issue by Onione-Tamiko** [tncykrkyl/csgo-advanced-drop#10]
![изображение](https://user-images.githubusercontent.com/98662900/226185741-842e4d51-564e-403f-9736-90ba6ea87181.png)
Recently everything worked!
What happened and when will it work?

And prime.napas.cc dont work(

**Comment by crashzk** [comment]
His website, which he used to host the web part, was closed. Web source files are now available for anyone who needs them.

**Comment by Onione-Tamiko** [comment]
> 
@crashzk
where are the source files

**Comment by crashzk** [comment]
Github: https://github.com/oppars01/csgo-advanced-drop

Folder `php`: https://github.com/oppars01/csgo-advanced-drop/tree/main/php

**Comment by Onione-Tamiko** [comment]
Hey... @crashzk 
https://api.steampowered.com/IEconItems_730/GetSchema/v2/?key=XXXXXXXXXXXXXXXXX&format=json&language=en
 
Result:
{
	"result": {
		"WebApiErrorMessage": "Method permanently disabled, see https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Economy_Items"
	}
}

maybe you know how to fix or replace?

**Comment by crashzk** [comment]
Yeah, I forgot, I talked to the author about it, apparently Steam removed this API and didn't share the new one, something like that.

![image](https://user-images.githubusercontent.com/32937653/227942066-863f6005-e6dc-4d3b-980b-0844257c250a.png)

We have to wait then, for now it keeps giving this error.
