### ISSUE TITLE
Error getting case prices

### ISSUE THREAD

**Issue by crashzk** [tncykrkyl/csgo-advanced-drop#4]
@tncykrkyl error related to getting prices for drops reoccurred, as previously reported in issues: https://github.com/tncykrkyl/csgo-advanced-drop/issues/1

![image](https://user-images.githubusercontent.com/32937653/202907696-bd336e5d-b540-4347-aaba-a74ea6eb727f.png)

![image](https://user-images.githubusercontent.com/32937653/202907711-033df2d9-1038-4785-be4f-dcb58e1413ac.png)

But I noticed that the API that the plugin uses to update prices is offline, could this be the reason? Any fixes I can apply?

https://csgo-turkiye.com/api/csgo-items?format=vdf&language=en
https://csgo-turkiye.com/api/csgo-items?format=json&language=en

**Comment by crashzk** [comment]
Would it be possible to provide this web file? So I can host my own web hosting.

**Comment by oppars01** [comment]
I have uploaded the web api file. Just editing the STEAM API is enough. When I look at the price issue, there is no obvious error on the installed servers. In the first screenshot, the price of the Dreams case can be drawn. Steam price query can sometimes give an error or not give the price when there are too many requests. That's probably the reason.

**Comment by crashzk** [comment]
Fix!
