### ISSUE TITLE
The plugin probably need update following CS:GO server update 02/02/2023

### ISSUE THREAD

**Issue by Pixon** [tncykrkyl/csgo-advanced-drop#7]
Hi and thanks for this usefull plugin.

On 02/02/2023 there was a an update that broke sourcemod and most of the plugins gamedata after this update the plugin is not working anymore withs following errors : 

02/03/2023 - 20:24:58: SourceMod error session started
L 02/03/2023 - 20:24:58: Info (map "achievement_idle") (file "/home/csgoserver/serverfiles/csgo/addons/sourcemod/logs/errors_20230203.log")
L 02/03/2023 - 20:24:58: [SM] Exception reported: [ csgo-turkiye.com Advanced Drop ] Failed to create SDKCall for CCSGameRules::RewardMatchEndDrops.
L 02/03/2023 - 20:24:58: [SM] Blaming: csgotr-advanced_drop.smx
L 02/03/2023 - 20:24:58: [SM] Call stack trace:
L 02/03/2023 - 20:24:58: [SM]   [0] SetFailState
L 02/03/2023 - 20:24:58: [SM]   [1] Line 57, D:\Pluginler\sourcemod-1.10.0-git6502-windows\addons\sourcemod\scripting\csgotr-advanced_drop.sp::OnPluginStart
L 02/03/2023 - 20:24:58: [SM] Unable to load plugin "csgotr-advanced_drop.smx": Error detected in plugin startup (see error logs)

The gamedate of the plugin from what I understood (Im really not an expert of the domain) need udpdate

**Comment by crashzk** [comment]
+1

**Comment by oppars01** [comment]
`"Games"
{
	"csgo"
	{
		"Offsets"
		{
			"OS"
			{
				"linux"		"1"
				"windows"	"2"
			}
		}
		"Addresses"
		{
			"DropForAllPlayersPatch"
			{
				"signature"	"Helper_FillServerReservationStateAndPlayers"
				"linux"
				{
					"offset"	"426"
				}
				"windows"
				{
					"offset"	"478"
				}
			}
		}
		"Functions"
		{
			"CCSGameRules::RecordPlayerItemDrop"
			{
				"signature"	"CCSGameRules::RecordPlayerItemDrop"
				"callconv"	"thiscall"
				"return"	"void"
				"this"		"ignore"
				"arguments"
				{
					"iteminfo"
					{
						"type"	"objectptr"
					}
				}
			}
		}
		"Signatures"
		{
			"CCSGameRules::RewardMatchEndDrops"
			{
				"library"		"server"
				"linux"			"\x55\x89\xE5\x57\x56\x53\x8D\x5D\xD4\x83\xEC\x44"
				"windows"		"\x55\x8B\xEC\x83\xE4\xF8\xA1\x2A\x2A\x2A\x2A\x83\xEC\x1C\xB9"
			}
			"CCSGameRules::RecordPlayerItemDrop"
			{
				"library"		"server"
				"linux"			"\x55\x89\xE5\x57\x56\x53\x83\xEC\x1C\x8B\x45\x08\x8B\x80\x2A\x2A\x2A\x2A\x85\xC0\x89"
				"windows"		"\x55\x8B\xEC\x53\x8B\xD9\x33\xD2\x56\x57\x8B\x7D\x08"
			}
			"Helper_FillServerReservationStateAndPlayers"
			{
				"library"		"server"
				"linux"			"\x55\x89\xE5\x57\x56\x53\x83\xEC\x78\xA1"
				"windows"		"\x55\x8B\xEC\x83\xEC\x64\x53\x8B\xD9\x8B\x0D"
			}
		}
	}
}`

**Comment by oppars01** [comment]
Can you try using the GameData above?

**Comment by Pixon** [comment]
Yes I'll try this and let you know, thanks

**Comment by Pixon** [comment]
It seem to work : 
![image](https://user-images.githubusercontent.com/10232885/216737983-1e04e9f5-d485-44cc-98d4-ecf34ec3462c.png)

Thanks for the fast answer :)

**Comment by oppars01** [comment]
Glad it worked. Tomorrow I will test it myself and upload the updated version to the code section.

**Comment by crashzk** [comment]
> `"Games" { "csgo" { "Offsets" { "OS" { "linux" "1" "windows" "2" } } "Addresses" { "DropForAllPlayersPatch" { "signature" "Helper_FillServerReservationStateAndPlayers" "linux" { "offset" "426" } "windows" { "offset" "478" } } } "Functions" { "CCSGameRules::RecordPlayerItemDrop" { "signature" "CCSGameRules::RecordPlayerItemDrop" "callconv" "thiscall" "return" "void" "this" "ignore" "arguments" { "iteminfo" { "type" "objectptr" } } } } "Signatures" { "CCSGameRules::RewardMatchEndDrops" { "library" "server" "linux" "\x55\x89\xE5\x57\x56\x53\x8D\x5D\xD4\x83\xEC\x44" "windows" "\x55\x8B\xEC\x83\xE4\xF8\xA1\x2A\x2A\x2A\x2A\x83\xEC\x1C\xB9" } "CCSGameRules::RecordPlayerItemDrop" { "library" "server" "linux" "\x55\x89\xE5\x57\x56\x53\x83\xEC\x1C\x8B\x45\x08\x8B\x80\x2A\x2A\x2A\x2A\x85\xC0\x89" "windows" "\x55\x8B\xEC\x53\x8B\xD9\x33\xD2\x56\x57\x8B\x7D\x08" } "Helper_FillServerReservationStateAndPlayers" { "library" "server" "linux" "\x55\x89\xE5\x57\x56\x53\x83\xEC\x78\xA1" "windows" "\x55\x8B\xEC\x83\xEC\x64\x53\x8B\xD9\x8B\x0D" } } } }`

Then we have a problem, I updated and it didn't work, it keeps giving error in the plugin.

```
L 02/03/2023 - 22:55:15: [SM] Error parsing gameconfig file "/home/clientes/OGP_User_Files/whmcs/2056/csgo/addons/sourcemod/gamedata/csgo_advanced_drop.games.txt":
L 02/03/2023 - 22:55:15: [SM] Error 9 on line 2, col 60: Line contained too many invalid tokens
L 02/03/2023 - 22:55:15: [SM] Exception reported: Unable to open csgo_advanced_drop.games: Line contained too many invalid tokens
L 02/03/2023 - 22:55:15: [SM] Blaming: csgo_advanced_drop.smx
L 02/03/2023 - 22:55:15: [SM] Call stack trace:
L 02/03/2023 - 22:55:15: [SM]   [0] LoadGameConfigFile
L 02/03/2023 - 22:55:15: [SM]   [1] Line 37, D:\Google Drive\ZK Servidores\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\csgo_advanced_drop.sp::OnPluginStart
L 02/03/2023 - 22:55:15: [SM] Unable to load plugin "csgo_advanced_drop.smx": Error detected in plugin startup (see error logs)
```

**Comment by Pixon** [comment]
Its because of the copy/paste of the message from github I think, try this file which should work
[advanced_drop.games.txt](https://github.com/oppars01/csgo-advanced-drop/files/10593758/advanced_drop.games.txt)

**Comment by crashzk** [comment]
> Its because of the copy/paste of the message from github I think, try this file which should work [advanced_drop.games.txt](https://github.com/oppars01/csgo-advanced-drop/files/10593758/advanced_drop.games.txt)

It worked!
