### ISSUE TITLE
Plugin does not give error, but it is not dropping items

### ISSUE THREAD

**Issue by FPSGuilherme** [tncykrkyl/csgo-advanced-drop#8]
I have already updated the signatures in gamedata and what I could notice is that the drops are not being requested during that delay (a message appears in the chat, but it doesn't really seem to me to request the drop), because I have a server with 40 constant players and since yesterday, only 4 drops and all of them coincided to be at the time of map change. 

Looking at the logs, I see this error:
```
[csgotr-advanced_drop.smx] [ csgo-turkiye.com Advanced Drop ] Not as we expected at DropForAllPlayersPatch, drop will not be available for all players.
```

**Comment by shaikhnedab** [comment]
facing same error and issue.

**Comment by oppars01** [comment]
Sorry, I don't know how to fix this error.

**Comment by rawensoft** [comment]
replace gamedata to this and it's gonna be work
[DropsSummoner.games.txt](https://github.com/oppars01/csgo-advanced-drop/files/10696530/DropsSummoner.games.txt)

**Comment by rawensoft** [comment]
better if u check this https://github.com/komashchenko/sourcemod-plugins/tree/master/DropsSummoner

**Comment by shaikhnedab** [comment]
thanks. its working now. @rawensoft

**Comment by crashzk** [comment]
I can confirm, gamedata from PR https://github.com/oppars01/csgo-advanced-drop/pull/9 solved the problem here too.
